name: CI Workflow

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '7.0'
  SOLUTION_FILE: 'Revue Crafters.sln'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Restore NuGet packages
      - name: Restore packages
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      # Build the solution
      - name: Build solution
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

      # Run all tests
      - name: Run tests
        run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      # Upload test results as artifact
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: '**/TestResults.trx'
